/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_albumtype {
  public final static sp_albumtype SP_ALBUMTYPE_ALBUM = new sp_albumtype("SP_ALBUMTYPE_ALBUM", spotifyJNI.SP_ALBUMTYPE_ALBUM_get());
  public final static sp_albumtype SP_ALBUMTYPE_SINGLE = new sp_albumtype("SP_ALBUMTYPE_SINGLE", spotifyJNI.SP_ALBUMTYPE_SINGLE_get());
  public final static sp_albumtype SP_ALBUMTYPE_COMPILATION = new sp_albumtype("SP_ALBUMTYPE_COMPILATION", spotifyJNI.SP_ALBUMTYPE_COMPILATION_get());
  public final static sp_albumtype SP_ALBUMTYPE_UNKNOWN = new sp_albumtype("SP_ALBUMTYPE_UNKNOWN", spotifyJNI.SP_ALBUMTYPE_UNKNOWN_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_albumtype swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_albumtype.class + " with value " + swigValue);
  }

  private sp_albumtype(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_albumtype(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_albumtype(String swigName, sp_albumtype swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_albumtype[] swigValues = { SP_ALBUMTYPE_ALBUM, SP_ALBUMTYPE_SINGLE, SP_ALBUMTYPE_COMPILATION, SP_ALBUMTYPE_UNKNOWN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

