/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_audio_buffer_stats {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sp_audio_buffer_stats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_audio_buffer_stats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_audio_buffer_stats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSamples(int value) {
    spotifyJNI.sp_audio_buffer_stats_samples_set(swigCPtr, this, value);
  }

  public int getSamples() {
    return spotifyJNI.sp_audio_buffer_stats_samples_get(swigCPtr, this);
  }

  public void setStutter(int value) {
    spotifyJNI.sp_audio_buffer_stats_stutter_set(swigCPtr, this, value);
  }

  public int getStutter() {
    return spotifyJNI.sp_audio_buffer_stats_stutter_get(swigCPtr, this);
  }

  public sp_audio_buffer_stats() {
    this(spotifyJNI.new_sp_audio_buffer_stats(), true);
  }

}
