/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_connectionstate {
  public final static sp_connectionstate SP_CONNECTION_STATE_LOGGED_OUT = new sp_connectionstate("SP_CONNECTION_STATE_LOGGED_OUT", spotifyJNI.SP_CONNECTION_STATE_LOGGED_OUT_get());
  public final static sp_connectionstate SP_CONNECTION_STATE_LOGGED_IN = new sp_connectionstate("SP_CONNECTION_STATE_LOGGED_IN", spotifyJNI.SP_CONNECTION_STATE_LOGGED_IN_get());
  public final static sp_connectionstate SP_CONNECTION_STATE_DISCONNECTED = new sp_connectionstate("SP_CONNECTION_STATE_DISCONNECTED", spotifyJNI.SP_CONNECTION_STATE_DISCONNECTED_get());
  public final static sp_connectionstate SP_CONNECTION_STATE_UNDEFINED = new sp_connectionstate("SP_CONNECTION_STATE_UNDEFINED", spotifyJNI.SP_CONNECTION_STATE_UNDEFINED_get());
  public final static sp_connectionstate SP_CONNECTION_STATE_OFFLINE = new sp_connectionstate("SP_CONNECTION_STATE_OFFLINE", spotifyJNI.SP_CONNECTION_STATE_OFFLINE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_connectionstate swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_connectionstate.class + " with value " + swigValue);
  }

  private sp_connectionstate(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_connectionstate(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_connectionstate(String swigName, sp_connectionstate swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_connectionstate[] swigValues = { SP_CONNECTION_STATE_LOGGED_OUT, SP_CONNECTION_STATE_LOGGED_IN, SP_CONNECTION_STATE_DISCONNECTED, SP_CONNECTION_STATE_UNDEFINED, SP_CONNECTION_STATE_OFFLINE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

