/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_imageformat {
  public final static sp_imageformat SP_IMAGE_FORMAT_UNKNOWN = new sp_imageformat("SP_IMAGE_FORMAT_UNKNOWN", spotifyJNI.SP_IMAGE_FORMAT_UNKNOWN_get());
  public final static sp_imageformat SP_IMAGE_FORMAT_JPEG = new sp_imageformat("SP_IMAGE_FORMAT_JPEG", spotifyJNI.SP_IMAGE_FORMAT_JPEG_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_imageformat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_imageformat.class + " with value " + swigValue);
  }

  private sp_imageformat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_imageformat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_imageformat(String swigName, sp_imageformat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_imageformat[] swigValues = { SP_IMAGE_FORMAT_UNKNOWN, SP_IMAGE_FORMAT_JPEG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

