/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_image_size {
  public final static sp_image_size SP_IMAGE_SIZE_NORMAL = new sp_image_size("SP_IMAGE_SIZE_NORMAL", spotifyJNI.SP_IMAGE_SIZE_NORMAL_get());
  public final static sp_image_size SP_IMAGE_SIZE_SMALL = new sp_image_size("SP_IMAGE_SIZE_SMALL", spotifyJNI.SP_IMAGE_SIZE_SMALL_get());
  public final static sp_image_size SP_IMAGE_SIZE_LARGE = new sp_image_size("SP_IMAGE_SIZE_LARGE", spotifyJNI.SP_IMAGE_SIZE_LARGE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_image_size swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_image_size.class + " with value " + swigValue);
  }

  private sp_image_size(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_image_size(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_image_size(String swigName, sp_image_size swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_image_size[] swigValues = { SP_IMAGE_SIZE_NORMAL, SP_IMAGE_SIZE_SMALL, SP_IMAGE_SIZE_LARGE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

