/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_playlist_callbacks {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sp_playlist_callbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_playlist_callbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_playlist_callbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTracks_added(SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__p_struct_sp_track_int_int_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_tracks_added_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__p_struct_sp_track_int_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__p_struct_sp_track_int_int_p_void__void getTracks_added() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_tracks_added_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__p_struct_sp_track_int_int_p_void__void(cPtr, false);
  }

  public void setTracks_removed(SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_tracks_removed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_p_void__void getTracks_removed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_tracks_removed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_p_void__void(cPtr, false);
  }

  public void setTracks_moved(SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_int_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_tracks_moved_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_int_p_void__void getTracks_moved() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_tracks_moved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__int_int_int_p_void__void(cPtr, false);
  }

  public void setPlaylist_renamed(SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_playlist_renamed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void getPlaylist_renamed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_playlist_renamed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void(cPtr, false);
  }

  public void setPlaylist_state_changed(SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_playlist_state_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void getPlaylist_state_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_playlist_state_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void(cPtr, false);
  }

  public void setPlaylist_update_in_progress(SWIGTYPE_p_f_p_struct_sp_playlist_bool_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_playlist_update_in_progress_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_bool_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_bool_p_void__void getPlaylist_update_in_progress() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_playlist_update_in_progress_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_bool_p_void__void(cPtr, false);
  }

  public void setPlaylist_metadata_updated(SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_playlist_metadata_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void getPlaylist_metadata_updated() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_playlist_metadata_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void(cPtr, false);
  }

  public void setTrack_created_changed(SWIGTYPE_p_f_p_struct_sp_playlist_int_p_struct_sp_user_int_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_track_created_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_int_p_struct_sp_user_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_int_p_struct_sp_user_int_p_void__void getTrack_created_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_track_created_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_int_p_struct_sp_user_int_p_void__void(cPtr, false);
  }

  public void setTrack_seen_changed(SWIGTYPE_p_f_p_struct_sp_playlist_int_bool_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_track_seen_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_int_bool_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_int_bool_p_void__void getTrack_seen_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_track_seen_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_int_bool_p_void__void(cPtr, false);
  }

  public void setDescription_changed(SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__char_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_description_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__char_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__char_p_void__void getDescription_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_description_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__char_p_void__void(cPtr, false);
  }

  public void setImage_changed(SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__unsigned_char_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_image_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__unsigned_char_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__unsigned_char_p_void__void getImage_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_image_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_q_const__unsigned_char_p_void__void(cPtr, false);
  }

  public void setTrack_message_changed(SWIGTYPE_p_f_p_struct_sp_playlist_int_p_q_const__char_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_track_message_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_int_p_q_const__char_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_int_p_q_const__char_p_void__void getTrack_message_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_track_message_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_int_p_q_const__char_p_void__void(cPtr, false);
  }

  public void setSubscribers_changed(SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void value) {
    spotifyJNI.sp_playlist_callbacks_subscribers_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void getSubscribers_changed() {
    long cPtr = spotifyJNI.sp_playlist_callbacks_subscribers_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlist_p_void__void(cPtr, false);
  }

  public sp_playlist_callbacks() {
    this(spotifyJNI.new_sp_playlist_callbacks(), true);
  }

}
