/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_playlist_offline_status {
  public final static sp_playlist_offline_status SP_PLAYLIST_OFFLINE_STATUS_NO = new sp_playlist_offline_status("SP_PLAYLIST_OFFLINE_STATUS_NO", spotifyJNI.SP_PLAYLIST_OFFLINE_STATUS_NO_get());
  public final static sp_playlist_offline_status SP_PLAYLIST_OFFLINE_STATUS_YES = new sp_playlist_offline_status("SP_PLAYLIST_OFFLINE_STATUS_YES", spotifyJNI.SP_PLAYLIST_OFFLINE_STATUS_YES_get());
  public final static sp_playlist_offline_status SP_PLAYLIST_OFFLINE_STATUS_DOWNLOADING = new sp_playlist_offline_status("SP_PLAYLIST_OFFLINE_STATUS_DOWNLOADING", spotifyJNI.SP_PLAYLIST_OFFLINE_STATUS_DOWNLOADING_get());
  public final static sp_playlist_offline_status SP_PLAYLIST_OFFLINE_STATUS_WAITING = new sp_playlist_offline_status("SP_PLAYLIST_OFFLINE_STATUS_WAITING", spotifyJNI.SP_PLAYLIST_OFFLINE_STATUS_WAITING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_playlist_offline_status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_playlist_offline_status.class + " with value " + swigValue);
  }

  private sp_playlist_offline_status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_playlist_offline_status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_playlist_offline_status(String swigName, sp_playlist_offline_status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_playlist_offline_status[] swigValues = { SP_PLAYLIST_OFFLINE_STATUS_NO, SP_PLAYLIST_OFFLINE_STATUS_YES, SP_PLAYLIST_OFFLINE_STATUS_DOWNLOADING, SP_PLAYLIST_OFFLINE_STATUS_WAITING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

