/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_playlistcontainer_callbacks {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sp_playlistcontainer_callbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_playlistcontainer_callbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_playlistcontainer_callbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlaylist_added(SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void value) {
    spotifyJNI.sp_playlistcontainer_callbacks_playlist_added_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void getPlaylist_added() {
    long cPtr = spotifyJNI.sp_playlistcontainer_callbacks_playlist_added_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void(cPtr, false);
  }

  public void setPlaylist_removed(SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void value) {
    spotifyJNI.sp_playlistcontainer_callbacks_playlist_removed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void getPlaylist_removed() {
    long cPtr = spotifyJNI.sp_playlistcontainer_callbacks_playlist_removed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_p_void__void(cPtr, false);
  }

  public void setPlaylist_moved(SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_int_p_void__void value) {
    spotifyJNI.sp_playlistcontainer_callbacks_playlist_moved_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_int_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_int_p_void__void getPlaylist_moved() {
    long cPtr = spotifyJNI.sp_playlistcontainer_callbacks_playlist_moved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_struct_sp_playlist_int_int_p_void__void(cPtr, false);
  }

  public void setContainer_loaded(SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_void__void value) {
    spotifyJNI.sp_playlistcontainer_callbacks_container_loaded_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_void__void getContainer_loaded() {
    long cPtr = spotifyJNI.sp_playlistcontainer_callbacks_container_loaded_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_playlistcontainer_p_void__void(cPtr, false);
  }

  public sp_playlistcontainer_callbacks() {
    this(spotifyJNI.new_sp_playlistcontainer_callbacks(), true);
  }

}
