/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_relation_type {
  public final static sp_relation_type SP_RELATION_TYPE_UNKNOWN = new sp_relation_type("SP_RELATION_TYPE_UNKNOWN", spotifyJNI.SP_RELATION_TYPE_UNKNOWN_get());
  public final static sp_relation_type SP_RELATION_TYPE_NONE = new sp_relation_type("SP_RELATION_TYPE_NONE", spotifyJNI.SP_RELATION_TYPE_NONE_get());
  public final static sp_relation_type SP_RELATION_TYPE_UNIDIRECTIONAL = new sp_relation_type("SP_RELATION_TYPE_UNIDIRECTIONAL", spotifyJNI.SP_RELATION_TYPE_UNIDIRECTIONAL_get());
  public final static sp_relation_type SP_RELATION_TYPE_BIDIRECTIONAL = new sp_relation_type("SP_RELATION_TYPE_BIDIRECTIONAL", spotifyJNI.SP_RELATION_TYPE_BIDIRECTIONAL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_relation_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_relation_type.class + " with value " + swigValue);
  }

  private sp_relation_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_relation_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_relation_type(String swigName, sp_relation_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_relation_type[] swigValues = { SP_RELATION_TYPE_UNKNOWN, SP_RELATION_TYPE_NONE, SP_RELATION_TYPE_UNIDIRECTIONAL, SP_RELATION_TYPE_BIDIRECTIONAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

