/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_subscribers {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sp_subscribers(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_subscribers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_subscribers(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(long value) {
    spotifyJNI.sp_subscribers_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return spotifyJNI.sp_subscribers_count_get(swigCPtr, this);
  }

  public void setSubscribers(SWIGTYPE_p_p_char value) {
    spotifyJNI.sp_subscribers_subscribers_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getSubscribers() {
    long cPtr = spotifyJNI.sp_subscribers_subscribers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public sp_subscribers() {
    this(spotifyJNI.new_sp_subscribers(), true);
  }

}
