/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_session_callbacks {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sp_session_callbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_session_callbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_session_callbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogged_in(SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void value) {
    spotifyJNI.sp_session_callbacks_logged_in_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void getLogged_in() {
    long cPtr = spotifyJNI.sp_session_callbacks_logged_in_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void(cPtr, false);
  }

  public void setLogged_out(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_logged_out_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getLogged_out() {
    long cPtr = spotifyJNI.sp_session_callbacks_logged_out_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setMetadata_updated(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_metadata_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getMetadata_updated() {
    long cPtr = spotifyJNI.sp_session_callbacks_metadata_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setConnection_error(SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void value) {
    spotifyJNI.sp_session_callbacks_connection_error_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void getConnection_error() {
    long cPtr = spotifyJNI.sp_session_callbacks_connection_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void(cPtr, false);
  }

  public void setMessage_to_user(SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void value) {
    spotifyJNI.sp_session_callbacks_message_to_user_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void getMessage_to_user() {
    long cPtr = spotifyJNI.sp_session_callbacks_message_to_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void(cPtr, false);
  }

  public void setNotify_main_thread(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_notify_main_thread_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getNotify_main_thread() {
    long cPtr = spotifyJNI.sp_session_callbacks_notify_main_thread_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setMusic_delivery(SWIGTYPE_p_f_p_struct_sp_session_p_q_const__struct_sp_audioformat_p_q_const__void_int__int value) {
    spotifyJNI.sp_session_callbacks_music_delivery_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_p_q_const__struct_sp_audioformat_p_q_const__void_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_p_q_const__struct_sp_audioformat_p_q_const__void_int__int getMusic_delivery() {
    long cPtr = spotifyJNI.sp_session_callbacks_music_delivery_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_p_q_const__struct_sp_audioformat_p_q_const__void_int__int(cPtr, false);
  }

  public void setPlay_token_lost(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_play_token_lost_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getPlay_token_lost() {
    long cPtr = spotifyJNI.sp_session_callbacks_play_token_lost_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setLog_message(SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void value) {
    spotifyJNI.sp_session_callbacks_log_message_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void getLog_message() {
    long cPtr = spotifyJNI.sp_session_callbacks_log_message_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void(cPtr, false);
  }

  public void setEnd_of_track(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_end_of_track_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getEnd_of_track() {
    long cPtr = spotifyJNI.sp_session_callbacks_end_of_track_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setStreaming_error(SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void value) {
    spotifyJNI.sp_session_callbacks_streaming_error_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void getStreaming_error() {
    long cPtr = spotifyJNI.sp_session_callbacks_streaming_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void(cPtr, false);
  }

  public void setUserinfo_updated(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_userinfo_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getUserinfo_updated() {
    long cPtr = spotifyJNI.sp_session_callbacks_userinfo_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setStart_playback(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_start_playback_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getStart_playback() {
    long cPtr = spotifyJNI.sp_session_callbacks_start_playback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setStop_playback(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_stop_playback_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getStop_playback() {
    long cPtr = spotifyJNI.sp_session_callbacks_stop_playback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setGet_audio_buffer_stats(SWIGTYPE_p_f_p_struct_sp_session_p_struct_sp_audio_buffer_stats__void value) {
    spotifyJNI.sp_session_callbacks_get_audio_buffer_stats_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_p_struct_sp_audio_buffer_stats__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_p_struct_sp_audio_buffer_stats__void getGet_audio_buffer_stats() {
    long cPtr = spotifyJNI.sp_session_callbacks_get_audio_buffer_stats_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_p_struct_sp_audio_buffer_stats__void(cPtr, false);
  }

  public void setOffline_status_updated(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_offline_status_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getOffline_status_updated() {
    long cPtr = spotifyJNI.sp_session_callbacks_offline_status_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setOffline_error(SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void value) {
    spotifyJNI.sp_session_callbacks_offline_error_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void getOffline_error() {
    long cPtr = spotifyJNI.sp_session_callbacks_offline_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void(cPtr, false);
  }

  public void setCredentials_blob_updated(SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void value) {
    spotifyJNI.sp_session_callbacks_credentials_blob_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void getCredentials_blob_updated() {
    long cPtr = spotifyJNI.sp_session_callbacks_credentials_blob_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_p_q_const__char__void(cPtr, false);
  }

  public void setConnectionstate_updated(SWIGTYPE_p_f_p_struct_sp_session__void value) {
    spotifyJNI.sp_session_callbacks_connectionstate_updated_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session__void getConnectionstate_updated() {
    long cPtr = spotifyJNI.sp_session_callbacks_connectionstate_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session__void(cPtr, false);
  }

  public void setScrobble_error(SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void value) {
    spotifyJNI.sp_session_callbacks_scrobble_error_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void getScrobble_error() {
    long cPtr = spotifyJNI.sp_session_callbacks_scrobble_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_enum_sp_error__void(cPtr, false);
  }

  public void setPrivate_session_mode_changed(SWIGTYPE_p_f_p_struct_sp_session_bool__void value) {
    spotifyJNI.sp_session_callbacks_private_session_mode_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_sp_session_bool__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_sp_session_bool__void getPrivate_session_mode_changed() {
    long cPtr = spotifyJNI.sp_session_callbacks_private_session_mode_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_sp_session_bool__void(cPtr, false);
  }

  public sp_session_callbacks() {
    this(spotifyJNI.new_sp_session_callbacks(), true);
  }

}
