/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public class sp_session_config {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public sp_session_config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sp_session_config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spotifyJNI.delete_sp_session_config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApi_version(int value) {
    spotifyJNI.sp_session_config_api_version_set(swigCPtr, this, value);
  }

  public int getApi_version() {
    return spotifyJNI.sp_session_config_api_version_get(swigCPtr, this);
  }

  public void setCache_location(String value) {
    spotifyJNI.sp_session_config_cache_location_set(swigCPtr, this, value);
  }

  public String getCache_location() {
    return spotifyJNI.sp_session_config_cache_location_get(swigCPtr, this);
  }

  public void setSettings_location(String value) {
    spotifyJNI.sp_session_config_settings_location_set(swigCPtr, this, value);
  }

  public String getSettings_location() {
    return spotifyJNI.sp_session_config_settings_location_get(swigCPtr, this);
  }

  public void setApplication_key(SWIGTYPE_p_void value) {
    spotifyJNI.sp_session_config_application_key_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getApplication_key() {
    long cPtr = spotifyJNI.sp_session_config_application_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setApplication_key_size(long value) {
    spotifyJNI.sp_session_config_application_key_size_set(swigCPtr, this, value);
  }

  public long getApplication_key_size() {
    return spotifyJNI.sp_session_config_application_key_size_get(swigCPtr, this);
  }

  public void setUser_agent(String value) {
    spotifyJNI.sp_session_config_user_agent_set(swigCPtr, this, value);
  }

  public String getUser_agent() {
    return spotifyJNI.sp_session_config_user_agent_get(swigCPtr, this);
  }

  public void setCallbacks(sp_session_callbacks value) {
    spotifyJNI.sp_session_config_callbacks_set(swigCPtr, this, sp_session_callbacks.getCPtr(value), value);
  }

  public sp_session_callbacks getCallbacks() {
    long cPtr = spotifyJNI.sp_session_config_callbacks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new sp_session_callbacks(cPtr, false);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    spotifyJNI.sp_session_config_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = spotifyJNI.sp_session_config_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setCompress_playlists(boolean value) {
    spotifyJNI.sp_session_config_compress_playlists_set(swigCPtr, this, value);
  }

  public boolean getCompress_playlists() {
    return spotifyJNI.sp_session_config_compress_playlists_get(swigCPtr, this);
  }

  public void setDont_save_metadata_for_playlists(boolean value) {
    spotifyJNI.sp_session_config_dont_save_metadata_for_playlists_set(swigCPtr, this, value);
  }

  public boolean getDont_save_metadata_for_playlists() {
    return spotifyJNI.sp_session_config_dont_save_metadata_for_playlists_get(swigCPtr, this);
  }

  public void setInitially_unload_playlists(boolean value) {
    spotifyJNI.sp_session_config_initially_unload_playlists_set(swigCPtr, this, value);
  }

  public boolean getInitially_unload_playlists() {
    return spotifyJNI.sp_session_config_initially_unload_playlists_get(swigCPtr, this);
  }

  public void setDevice_id(String value) {
    spotifyJNI.sp_session_config_device_id_set(swigCPtr, this, value);
  }

  public String getDevice_id() {
    return spotifyJNI.sp_session_config_device_id_get(swigCPtr, this);
  }

  public void setProxy(String value) {
    spotifyJNI.sp_session_config_proxy_set(swigCPtr, this, value);
  }

  public String getProxy() {
    return spotifyJNI.sp_session_config_proxy_get(swigCPtr, this);
  }

  public void setProxy_username(String value) {
    spotifyJNI.sp_session_config_proxy_username_set(swigCPtr, this, value);
  }

  public String getProxy_username() {
    return spotifyJNI.sp_session_config_proxy_username_get(swigCPtr, this);
  }

  public void setProxy_password(String value) {
    spotifyJNI.sp_session_config_proxy_password_set(swigCPtr, this, value);
  }

  public String getProxy_password() {
    return spotifyJNI.sp_session_config_proxy_password_get(swigCPtr, this);
  }

  public void setCa_certs_filename(String value) {
    spotifyJNI.sp_session_config_ca_certs_filename_set(swigCPtr, this, value);
  }

  public String getCa_certs_filename() {
    return spotifyJNI.sp_session_config_ca_certs_filename_get(swigCPtr, this);
  }

  public void setTracefile(String value) {
    spotifyJNI.sp_session_config_tracefile_set(swigCPtr, this, value);
  }

  public String getTracefile() {
    return spotifyJNI.sp_session_config_tracefile_get(swigCPtr, this);
  }

  public sp_session_config() {
    this(spotifyJNI.new_sp_session_config(), true);
  }

}
