/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_scrobbling_state {
  public final static sp_scrobbling_state SP_SCROBBLING_STATE_USE_GLOBAL_SETTING = new sp_scrobbling_state("SP_SCROBBLING_STATE_USE_GLOBAL_SETTING", spotifyJNI.SP_SCROBBLING_STATE_USE_GLOBAL_SETTING_get());
  public final static sp_scrobbling_state SP_SCROBBLING_STATE_LOCAL_ENABLED = new sp_scrobbling_state("SP_SCROBBLING_STATE_LOCAL_ENABLED", spotifyJNI.SP_SCROBBLING_STATE_LOCAL_ENABLED_get());
  public final static sp_scrobbling_state SP_SCROBBLING_STATE_LOCAL_DISABLED = new sp_scrobbling_state("SP_SCROBBLING_STATE_LOCAL_DISABLED", spotifyJNI.SP_SCROBBLING_STATE_LOCAL_DISABLED_get());
  public final static sp_scrobbling_state SP_SCROBBLING_STATE_GLOBAL_ENABLED = new sp_scrobbling_state("SP_SCROBBLING_STATE_GLOBAL_ENABLED", spotifyJNI.SP_SCROBBLING_STATE_GLOBAL_ENABLED_get());
  public final static sp_scrobbling_state SP_SCROBBLING_STATE_GLOBAL_DISABLED = new sp_scrobbling_state("SP_SCROBBLING_STATE_GLOBAL_DISABLED", spotifyJNI.SP_SCROBBLING_STATE_GLOBAL_DISABLED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_scrobbling_state swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_scrobbling_state.class + " with value " + swigValue);
  }

  private sp_scrobbling_state(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_scrobbling_state(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_scrobbling_state(String swigName, sp_scrobbling_state swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_scrobbling_state[] swigValues = { SP_SCROBBLING_STATE_USE_GLOBAL_SETTING, SP_SCROBBLING_STATE_LOCAL_ENABLED, SP_SCROBBLING_STATE_LOCAL_DISABLED, SP_SCROBBLING_STATE_GLOBAL_ENABLED, SP_SCROBBLING_STATE_GLOBAL_DISABLED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

