/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_social_provider {
  public final static sp_social_provider SP_SOCIAL_PROVIDER_SPOTIFY = new sp_social_provider("SP_SOCIAL_PROVIDER_SPOTIFY");
  public final static sp_social_provider SP_SOCIAL_PROVIDER_FACEBOOK = new sp_social_provider("SP_SOCIAL_PROVIDER_FACEBOOK");
  public final static sp_social_provider SP_SOCIAL_PROVIDER_LASTFM = new sp_social_provider("SP_SOCIAL_PROVIDER_LASTFM");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_social_provider swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_social_provider.class + " with value " + swigValue);
  }

  private sp_social_provider(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_social_provider(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_social_provider(String swigName, sp_social_provider swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_social_provider[] swigValues = { SP_SOCIAL_PROVIDER_SPOTIFY, SP_SOCIAL_PROVIDER_FACEBOOK, SP_SOCIAL_PROVIDER_LASTFM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

