/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_track_availability {
  public final static sp_track_availability SP_TRACK_AVAILABILITY_UNAVAILABLE = new sp_track_availability("SP_TRACK_AVAILABILITY_UNAVAILABLE", spotifyJNI.SP_TRACK_AVAILABILITY_UNAVAILABLE_get());
  public final static sp_track_availability SP_TRACK_AVAILABILITY_AVAILABLE = new sp_track_availability("SP_TRACK_AVAILABILITY_AVAILABLE", spotifyJNI.SP_TRACK_AVAILABILITY_AVAILABLE_get());
  public final static sp_track_availability SP_TRACK_AVAILABILITY_NOT_STREAMABLE = new sp_track_availability("SP_TRACK_AVAILABILITY_NOT_STREAMABLE", spotifyJNI.SP_TRACK_AVAILABILITY_NOT_STREAMABLE_get());
  public final static sp_track_availability SP_TRACK_AVAILABILITY_BANNED_BY_ARTIST = new sp_track_availability("SP_TRACK_AVAILABILITY_BANNED_BY_ARTIST", spotifyJNI.SP_TRACK_AVAILABILITY_BANNED_BY_ARTIST_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_track_availability swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_track_availability.class + " with value " + swigValue);
  }

  private sp_track_availability(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_track_availability(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_track_availability(String swigName, sp_track_availability swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_track_availability[] swigValues = { SP_TRACK_AVAILABILITY_UNAVAILABLE, SP_TRACK_AVAILABILITY_AVAILABLE, SP_TRACK_AVAILABILITY_NOT_STREAMABLE, SP_TRACK_AVAILABILITY_BANNED_BY_ARTIST };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

