/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_toplisttype {
  public final static sp_toplisttype SP_TOPLIST_TYPE_ARTISTS = new sp_toplisttype("SP_TOPLIST_TYPE_ARTISTS", spotifyJNI.SP_TOPLIST_TYPE_ARTISTS_get());
  public final static sp_toplisttype SP_TOPLIST_TYPE_ALBUMS = new sp_toplisttype("SP_TOPLIST_TYPE_ALBUMS", spotifyJNI.SP_TOPLIST_TYPE_ALBUMS_get());
  public final static sp_toplisttype SP_TOPLIST_TYPE_TRACKS = new sp_toplisttype("SP_TOPLIST_TYPE_TRACKS", spotifyJNI.SP_TOPLIST_TYPE_TRACKS_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_toplisttype swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_toplisttype.class + " with value " + swigValue);
  }

  private sp_toplisttype(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_toplisttype(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_toplisttype(String swigName, sp_toplisttype swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_toplisttype[] swigValues = { SP_TOPLIST_TYPE_ARTISTS, SP_TOPLIST_TYPE_ALBUMS, SP_TOPLIST_TYPE_TRACKS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

