/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_toplistregion {
  public final static sp_toplistregion SP_TOPLIST_REGION_EVERYWHERE = new sp_toplistregion("SP_TOPLIST_REGION_EVERYWHERE", spotifyJNI.SP_TOPLIST_REGION_EVERYWHERE_get());
  public final static sp_toplistregion SP_TOPLIST_REGION_USER = new sp_toplistregion("SP_TOPLIST_REGION_USER", spotifyJNI.SP_TOPLIST_REGION_USER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_toplistregion swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_toplistregion.class + " with value " + swigValue);
  }

  private sp_toplistregion(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_toplistregion(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_toplistregion(String swigName, sp_toplistregion swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_toplistregion[] swigValues = { SP_TOPLIST_REGION_EVERYWHERE, SP_TOPLIST_REGION_USER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

