/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public final class sp_track_offline_status {
  public final static sp_track_offline_status SP_TRACK_OFFLINE_NO = new sp_track_offline_status("SP_TRACK_OFFLINE_NO", spotifyJNI.SP_TRACK_OFFLINE_NO_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_WAITING = new sp_track_offline_status("SP_TRACK_OFFLINE_WAITING", spotifyJNI.SP_TRACK_OFFLINE_WAITING_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_DOWNLOADING = new sp_track_offline_status("SP_TRACK_OFFLINE_DOWNLOADING", spotifyJNI.SP_TRACK_OFFLINE_DOWNLOADING_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_DONE = new sp_track_offline_status("SP_TRACK_OFFLINE_DONE", spotifyJNI.SP_TRACK_OFFLINE_DONE_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_ERROR = new sp_track_offline_status("SP_TRACK_OFFLINE_ERROR", spotifyJNI.SP_TRACK_OFFLINE_ERROR_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_DONE_EXPIRED = new sp_track_offline_status("SP_TRACK_OFFLINE_DONE_EXPIRED", spotifyJNI.SP_TRACK_OFFLINE_DONE_EXPIRED_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_LIMIT_EXCEEDED = new sp_track_offline_status("SP_TRACK_OFFLINE_LIMIT_EXCEEDED", spotifyJNI.SP_TRACK_OFFLINE_LIMIT_EXCEEDED_get());
  public final static sp_track_offline_status SP_TRACK_OFFLINE_DONE_RESYNC = new sp_track_offline_status("SP_TRACK_OFFLINE_DONE_RESYNC", spotifyJNI.SP_TRACK_OFFLINE_DONE_RESYNC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sp_track_offline_status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sp_track_offline_status.class + " with value " + swigValue);
  }

  private sp_track_offline_status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sp_track_offline_status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sp_track_offline_status(String swigName, sp_track_offline_status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sp_track_offline_status[] swigValues = { SP_TRACK_OFFLINE_NO, SP_TRACK_OFFLINE_WAITING, SP_TRACK_OFFLINE_DOWNLOADING, SP_TRACK_OFFLINE_DONE, SP_TRACK_OFFLINE_ERROR, SP_TRACK_OFFLINE_DONE_EXPIRED, SP_TRACK_OFFLINE_LIMIT_EXCEEDED, SP_TRACK_OFFLINE_DONE_RESYNC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

