/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cs4720.moodmusic;

public interface spotifyConstants {
  public final static int SPOTIFY_API_VERSION = spotifyJNI.SPOTIFY_API_VERSION_get();
}
